
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs/status
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - jobs/status
  verbs:
  - get
- apiGroups:
  - sipp.alexandrevilain.dev
  resources:
  - sippscenario
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sipp.alexandrevilain.dev
  resources:
  - sippscenario/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sipp.alexandrevilain.dev
  resources:
  - sippscenarioruns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sipp.alexandrevilain.dev
  resources:
  - sippscenarioruns/status
  verbs:
  - get
  - patch
  - update
