# permissions for end users to view sippscenarioruns.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sippscenariorun-viewer-role
rules:
- apiGroups:
  - sipp.alexandrevilain.dev
  resources:
  - sippscenarioruns
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sipp.alexandrevilain.dev
  resources:
  - sippscenarioruns/status
  verbs:
  - get
