# permissions for end users to edit sippscenarioruns.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sippscenariorun-editor-role
rules:
- apiGroups:
  - sipp.alexandrevilain.dev
  resources:
  - sippscenarioruns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sipp.alexandrevilain.dev
  resources:
  - sippscenarioruns/status
  verbs:
  - get
