# permissions for end users to edit sippscenarios.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sippscenario-editor-role
rules:
- apiGroups:
  - sipp.alexandrevilain.dev
  resources:
  - sippscenarios
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sipp.alexandrevilain.dev
  resources:
  - sippscenarios/status
  verbs:
  - get
