# permissions for end users to view sippscenarios.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sippscenario-viewer-role
rules:
- apiGroups:
  - sipp.alexandrevilain.dev
  resources:
  - sippscenarios
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sipp.alexandrevilain.dev
  resources:
  - sippscenarios/status
  verbs:
  - get
